### ISSUE TITLE
run SWRL rules

### ISSUE THREAD

**Issue by MidouDali** [protegeproject/swrlapi-drools-engine#5]
Hi,
I used a SWRLRuleEngine to execute a SWRL rule in a OWL ontology. I used the method infer().
The number of the inferred axioms (by the rule) is 4 but the method getInferredOWLAxioms() returns many other axioms. I want to understand how Drools execute SWRL rules.
may be it's a reasoner not only a rule engine
How can I filter the axioms inferred by the SWRL rule?
thanks

**Comment by martinjoconnor** [comment]
The implementation is also an OWL (2 RL) reasoner.

See: http://ceur-ws.org/Vol-849/paper_31.pdf 

You can use SQWRL and the associated SQWRL API to get the inferences you are interested in.

See: https://github.com/protegeproject/swrlapi/wiki/SQWRL

Martin

**Comment by MidouDali** [comment]
Thank you,
Is it possible to run only a rule engine and disable other reasoning services?

**Comment by martinjoconnor** [comment]
You can call <tt>getOWLRLEngine</tt> on the <tt>SWRLRuleEngine</tt> and call <tt>disableAll</tt> on the returned object.

**Comment by MidouDali** [comment]
thanks
